### ISSUE TITLE
How to skip printing values same in both structures?

### ISSUE THREAD

**Issue by holyjak** [lambdaisland/deep-diff2#13]
How to skip printing values same in both structures? I am sorry, I am overwhelmed by fipp and puget and haven't managed to understand how to only print +/-/mismatches. Is there a way to override `print-other` to be a noop or something? Sorry and thank you!

**Comment by plexus** [comment]
This is not currently supported.

**Comment by holyjak** [comment]
Ah, ok. Thank you.

**Comment by awb99** [comment]
is this still not supported?
I had a look at the diff datastructure. seems changes are of a special type, so one could filter the keys that way.

**Comment by plexus** [comment]
If it had been you would probably see it mentioned here. I don't think anyone has stepped up yet to implement this.

**Comment by hsartoris-bard** [comment]
This isn't a solution in terms of dropping things while diffing or while printing, but it's functional as an intermediate step:

https://gist.github.com/hsartoris-bard/856d79d3a13f6cafaaa6e5079c76cd97

Even for relatively small data, the time cost incurred postwalking the diff is often negligible compared to how much faster rendering the diff is without the unchanged values.

**Comment by humorless** [comment]
> This isn't a solution in terms of dropping things while diffing or while printing, but it's functional as an intermediate step:
> 
> https://gist.github.com/hsartoris-bard/856d79d3a13f6cafaaa6e5079c76cd97
> 
> Even for relatively small data, the time cost incurred postwalking the diff is often negligible compared to how much faster rendering the diff is without the unchanged values.

Run the gist with the newest main commit, it does not work.

**Comment by humorless** [comment]
> hsartoris-bard

My friend kindly pointed out my English expression can probably make people misinterpret my intention. What I want to express is: "hi, I've tried running this code on the latest main branch, but it doesn't seem to be working anymore."

The code base sometimes changes quickly (so the gist does not work now), but the gist actually provided a good way to help me understand the issue.

**Comment by humorless** [comment]
An modified version of the solution provided by @hsartoris-bard 
https://gist.github.com/humorless/166ead294433179abb0b840305950914

**Comment by plexus** [comment]
This is great @humorless , let's add that remove-unchanged function in so at least we have API for this, we can consider separately how to expose this in kaocha.

**Comment by humorless** [comment]
In the newest release, there is a new function `minimize`, which can solve this issue. https://github.com/lambdaisland/deep-diff2#minimizing
