### ISSUE TITLE
Parameterize color schemes

### ISSUE THREAD

**Issue by alysbrooks** [lambdaisland/deep-diff2#41]
Currently, colors are hard-coded, but there are various situations where you might want to set different colors:

- To ensure adequate contrast on a different background
- To ensure readability by people who are colorblind
- To match your editor or main diff tool's color scheme.

In addition to general usefulness, parameterizing color schemes may address #14 and would be required for https://github.com/lambdaisland/kaocha/issues/403. 

- [ ] Allow for multiple built-in schemes: at least dark and light, and possibly a colorblind friendly scheme (if we can't make the dark and light schemes adequately colorblind) or a "classic" scheme if we end up tweaking colors.
- [ ] Allow for customization of the scheme

**Comment by humorless** [comment]
@alysbrooks @plexus 

I made some experiments. Actually, I can change the color to even 256 color without changing any single line of code. 

For example, if I change the `:lambdaisland.deep-diff2.printer-impl/deletion` from `[:red]` to ` [:bg-256 5 13]`, the color code it outputs will change from `\u001b[31m` to `\u001b[48;5;13m` 

**Screen shot** 
<img width="1055" alt="截圖 2023-04-06 下午5 25 45" src="https://user-images.githubusercontent.com/3061798/230334597-96662a08-7aab-40de-84e3-7ea7c7422a28.png">

```
user=> (use 'lambdaisland.deep-diff2)
nil
user=> (def color-printer (printer {:color-scheme {:lambdaisland.deep-diff2.printer-impl/deletion [:bg-256 5 13]}}))
#'user/color-printer
user=> (pretty-print (diff {:a 1} {:b 2}) color-printer)
{+:b 2, -:a 1}
```

**Comment by humorless** [comment]
Oh, after reading [related issues](https://github.com/lambdaisland/deep-diff2/issues/14#issuecomment-534238261) more carefully, I find out that there are `ansi.clj` can controll more than I thought.

**Comment by alysbrooks** [comment]
Reading through the code and this discussion, I think we should take the following steps:
1. Document how to set up a custom printer
1. Optionally, create a helper function to make it easier to set custom named colors or RGB colors. `lambdaisland.deep-diff2.printer-impl/puget-printer` isn't that complicated, but there's quite a bit of set up that's orthogonal.
1. Expose configuration in Kaocha.

I think @humorless and I could split these among ourselves, unless you have time/interest, @plexus?

**Comment by plexus** [comment]
Sounds good, you can go for it.

**Comment by metametadata** [comment]
```clj
user=> (use 'lambdaisland.deep-diff2)
nil
user=> (def color-printer (printer {:color-scheme {:lambdaisland.deep-diff2.printer-impl/deletion [:bg-256 5 13]}}))
#'user/color-printer
user=> (pretty-print (diff {:a 1} {:b 2}) color-printer)
{+:b 2, -:a 1}
```

This example from README unexpectedly resets all the other default `:color-scheme` values. So for example, insertions will not be highlighted anymore. 

The cause is in how `opts` are merged with the defaults in `lambdaisland.deep-diff2.printer-impl/puget-printer`.

<hr/>

It's also surprising to propose using `lambdaisland.deep-diff2.printer-impl` as it's an internal namespace.

**Comment by humorless** [comment]
@metametadata 

Based on your points, I would propose to fix this like this:

1. Logic Level: Use `update + merge`
Instead of performing a top-level merge on the entire opts map, the function should specifically merge the inner :color-scheme map. This prevents the user's input from wiping out the default color keys.

```
(defn puget-printer
  ([] (puget-printer {}))
  ([opts]
   (let [extra-handlers (:extra-handlers opts)
         ;; 1. Define the default color scheme
         default-colors {::deletion  [:red]
                         ::insertion [:green]
                         ::other     [:yellow]
                         :boolean    [:bold :cyan]
                         :tag        [:magenta]}
         ;; 2. Merge user-provided colors into the defaults
         user-colors    (:color-scheme opts)
         merged-colors  (merge default-colors user-colors)]
     
     (puget-printer/pretty-printer 
      (merge {:width           (or *print-length* 100)
              :print-color     true
              :color-scheme    merged-colors ; Use the merged result
              :print-handlers  (dispatch/chained-lookup
                                (print-handler-resolver extra-handlers)
                                puget-printer/common-handlers)}
             ;; Dissoc :color-scheme here so it doesn't overwrite the merged version
             (dissoc opts :extra-handlers :color-scheme))))))
```

2. Architecture Level: Simplify the API Keywords

To prevent users from having to reference `lambdaisland.deep-diff2.printer-impl/deletion`, the library should provide a mapping layer. This allows users to pass simple keywords like `:deletion`, which are then translated to the internal namespaced keys.

```
(defn- normalize-colors
  "Translates user-friendly keys to internal namespaced keys."
  [colors]
  (let [mapping {:deletion  ::deletion
                 :insertion ::insertion
                 :other     ::other}]
    (reduce-kv (fn [m k v]
                 (assoc m (get mapping k k) v)) ;; Fallback to original key if not in mapping
               {}
               colors)))

;; Inside puget-printer:
(let [user-colors   (normalize-colors (:color-scheme opts))
      merged-colors (merge default-colors user-colors)]
  ...)
```

**Comment by humorless** [comment]
https://github.com/lambdaisland/deep-diff2/pull/56
