### ISSUE TITLE
Hashmap key order shouldn't matter

### ISSUE THREAD

**Issue by pesterhazy** [lambdaisland/deep-diff2#47]
It shouldn't matter in which order I add keys to a hashmap:

```
(ddiff/diff {:name "Alyysa P Hacker" :age 40} {:age 40 :name "Alyssa P Hacker"})
```

Expected

```
{:name #lambdaisland.deep_diff2.diff_impl.Mismatch{:- "Alyysa P Hacker", :+ "Alyssa P Hacker"}, :age 40}
```

Actual

The `:age` key is removed and re-added:

```
{#lambdaisland.deep_diff2.diff_impl.Insertion{:+ :age} 40, :name #lambdaisland.deep_diff2.diff_impl.Mismatch{:- "Alyysa P Hacker", :+ "Alyssa P Hacker"}, #lambdaisland.deep_diff2.diff_impl.Deletion{:- :age} 40}
```

**Comment by alysbrooks** [comment]
Comparing different versions, my first guess is that this was caused by #45. @latacora-paul, do you have time to look into this?

**Comment by RutledgePaulV** [comment]
> @latacora-paul, do you have time to look into this?

Sure, here's a PR that stops using the sequential del+ins that is causing the issue for maps and adds a test for this scenario: 

https://github.com/lambdaisland/deep-diff2/pull/48/files
